title: My GitHub Pages Blog
description: Personal thoughts on the spirituality of rock and roll song lyrics and various other topics including technology, programming, and life.
theme: minima   # optional, you can remove if using custom layouts
